"""Source-only native-history capture, never benchmark QA.

The owner runs this suite sequentially in its isolated signed-ledger fixture.
The only subprocess permitted by its positive fixture is the registered
private signed-ledger keeper; gbrain/model/scoring/publishing are prohibited.

Proposed public API: siabench.capture_native_history(*, corpus,
chain_registry, chain_names). It returns the existing admitted capture schema,
with a separately named source-only generator and complete resolver cache.
No source-history completeness, idle-gist eligibility, or cognitive win follows
from this capture. Missing provenance is not the same as no QA relevance.

Legacy characterization is SEPARATE from the future-API RED tests:
  root_characterize_legacy_bytes() -> exact canonical packet bytes
  root_compare_legacy_bytes(expected=..., expected_sha256=...) -> None
Root must retain the FIRST packet and its independently observed wire digest
BEFORE production extraction. The compare function never updates a golden.
Both legacy default and opt-in bundles and every exported byte are retained.
No post-extraction-default versus post-extraction-opt-in comparison substitutes
for that pre-extraction authority.

The fixed fixture signs literal rows with its existing deterministic test key.
Current source projects those rows without clock input; verifier basename and
launch provenance redact temporary paths, and exports have no observed wall
timestamp. Verifier bytes, rendering/projector behavior, declared constants,
and relevant fixture source must therefore remain fixed across comparison.
Root should retain source/interpreter provenance separately; implementation
source itself is expected to change and is not removed from an output payload.
If a new varying field appears, refuse the comparison and fix the fixture or
explain the semantic change; never strip, normalize, or relearn that field.
"""

import ast
import base64
import contextlib
import fcntl
import hashlib
import inspect
import json
import os
from pathlib import Path
import stat
import unittest
from unittest import mock

from tests import test_cognitive_history_capture as capture_tests


SOURCE_GENERATOR_SCHEMA = "sia-native-source-capture-v1"
SOURCE_ONLY_NON_CLAIM = (
    "No questions, answer keys, splits, retrieval scores, or cognitive wins "
    "are generated by this source-only capture."
)
SOURCE_AUTHORITY_NON_CLAIMS = (
    "keeper verification authenticates rows, not memory-system correctness",
    "absence is scoped to the keeper-accepted observed ledger snapshot",
    "before/after byte, inode, metadata, and verifier-digest checks "
    "do not exclude a same-user in-place ABA completed between observations",
    "private state views preserve captured bytes and mode bits, not "
    "other inode metadata, pathname identity, or lock leases seen "
    "by the verifier",
    "the verifier digest binds the registered executable or script, "
    "not every library, interpreter, kernel, or hardware dependency it loads",
    "generation binding covers registered chain inputs, not undeclared "
    "data paths opened internally by verifier code",
    "strict format parsing checks row spelling and linkage after keeper "
    "success; it does not independently re-run signature verification",
    "Custos ledger intake does not re-open or re-hash files named by "
    "its signed custody rows",
    "consolidation-index lineage proves retention of an exact event "
    "occurrence, not that every answer token remains verbatim in the "
    "epoch summary",
)
REFUSALS = (ValueError, OSError, RuntimeError)


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False, allow_nan=False).encode("utf-8")


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def _tree_bytes(directory):
    """Fixture-only complete file roster; no real machine paths are supplied."""
    result = {}
    for root, directories, files in os.walk(directory, followlinks=False):
        for name in sorted(directories + files):
            path = Path(root) / name
            info = path.lstat()
            relative = path.relative_to(directory).as_posix()
            if stat.S_ISDIR(info.st_mode):
                result[relative] = {"kind": "directory"}
            elif stat.S_ISREG(info.st_mode):
                result[relative] = {
                    "kind": "file", "mode": stat.S_IMODE(info.st_mode),
                    "raw_base64": base64.b64encode(path.read_bytes()).decode("ascii"),
                }
            else:
                raise AssertionError("unexpected fixture alias or special file: " + relative)
    return result


class NativeHistoryCapture(unittest.TestCase):
    def setUp(self):
        # Compose the established fixture; do not inherit or duplicate its
        # previously frozen tests. Its helpers only modify private test files.
        self.fixture = capture_tests.CognitiveHistoryCapture(methodName="runTest")
        self.addCleanup(self.fixture.doCleanups)
        self.fixture.setUp()
        self.bench = self.fixture.bench
        self.lib = self.bench.sialib
        self.history = self.fixture._history_module()
        self.root = self.fixture.root
        self.corpus = Path(self.fixture.corpus)
        self.registry = self.fixture.registry
        self.stack = contextlib.ExitStack()
        self.addCleanup(self.stack.close)
        # Real owner/lifecycle operations remain inside this individual fixture.
        # The keeper's executable remains the existing registered test source.
        for name, relative in (
                ("HOME", "."), ("SHARE", "share"), ("STATE", "state"), ("BIN", "bin"),
                ("CORPUS_OWNER_LOCK", "state/corpus-owner.lock"),
                ("LIFECYCLE_LOCK", "state/lifecycle.lock"),
                ("LIFECYCLE_TOMBSTONE", "state/lifecycle-removed"),
                ("RESTORE_BARRIER_PATH", "restore/in-progress.json"),
                ("RESTORE_MASK_PATH", "restore/runtime-mask"),
                ("RESTORE_SUPERVISOR_PATH", "restore/supervisor.json")):
            self.stack.enter_context(mock.patch.object(
                self.lib, name, str(self.root / relative)))
        self.stack.enter_context(mock.patch.object(self.lib, "CORPUS", str(self.corpus)))
        self.stack.enter_context(mock.patch.object(self.bench, "CORPUS", str(self.corpus)))

    def _api(self):
        function = getattr(self.bench, "capture_native_history", None)
        self.assertTrue(callable(function), "missing source-only native capture API")
        return function

    @contextlib.contextmanager
    def _source_only(self):
        # These are actual owners used by the current benchmark/core paths.
        # Do not patch the generic process runner: the private keeper is real.
        with contextlib.ExitStack() as stack:
            for name in (
                    "build_ledger_dataset", "_require_usable_bundle", "_question_id",
                    "_audit_questions", "_cap_questions", "_assign_splits",
                    "build_questions", "evaluate_retrieval", "score_answer_file",
                    "run_quick", "run_legacy", "write_dataset", "_atomic_text", "_engine"):
                self.assertTrue(hasattr(self.bench, name), name)
                stack.enter_context(mock.patch.object(
                    self.bench, name,
                    side_effect=AssertionError("forbidden QA/engine/artifact path: " + name)))
            for name in ("gbrain", "gbrain_call", "brain_sync", "brainstem_owner",
                         "ledger_append", "durable_ledger_append", "corpus_origin",
                         "atomic_write", "write_page", "write_json"):
                if hasattr(self.lib, name):
                    stack.enter_context(mock.patch.object(
                        self.lib, name,
                        side_effect=AssertionError("forbidden runtime path: " + name)))
            yield

    def _call(self, *, names=None, registry=None):
        function = self._api()
        with self._source_only():
            return function(
                corpus=str(self.corpus),
                chain_registry=self.registry if registry is None else registry,
                chain_names=["aegis"] if names is None else names)

    def _assert_owned(self):
        self.assertGreater(self.lib._CORPUS_OWNER_DEPTH.get(), 0)
        held = os.fstat(self.lib._CORPUS_OWNER_FD.get())
        descriptor = os.open(self.lib.CORPUS_OWNER_LOCK,
                             os.O_RDWR | os.O_NOFOLLOW | os.O_CLOEXEC)
        try:
            named = os.fstat(descriptor)
            self.assertEqual((held.st_dev, held.st_ino), (named.st_dev, named.st_ino))
            with self.assertRaises(BlockingIOError):
                fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        finally:
            os.close(descriptor)

    def _assert_released(self):
        descriptor = os.open(self.lib.CORPUS_OWNER_LOCK,
                             os.O_RDWR | os.O_NOFOLLOW | os.O_CLOEXEC)
        try:
            fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
            fcntl.flock(descriptor, fcntl.LOCK_UN)
        finally:
            os.close(descriptor)

    def _assert_capture(self, capture):
        self.assertEqual(capture["schema"], self.history.SCHEMA)
        self.assertEqual(self.history.admit_capture(capture), capture)
        self.assertEqual(capture["capture_sha256"], sha(canonical({
            key: value for key, value in capture.items() if key != "capture_sha256"})))
        self.assertEqual(capture["non_claims"], list(self.history.NON_CLAIMS))
        self.assertEqual(capture["generator"], {
            "schema": SOURCE_GENERATOR_SCHEMA, "version": self.bench.GENERATOR_VERSION})
        self.assertEqual(capture["scope"], {
            "kind": "verified-ledger-projection-cache", "entire_corpus": False})
        self.assertIn(SOURCE_ONLY_NON_CLAIM, capture["source_non_claims"])
        for non_claim in SOURCE_AUTHORITY_NON_CLAIMS:
            self.assertIn(non_claim, capture["source_non_claims"])
        self.assertEqual(capture["generation_exclusions"], [])
        for name in ("questions", "answers", "answer_key", "queries", "splits",
                     "calibration_policy", "scores", "benchmark_wins"):
            self.assertNotIn(name, capture)

    def test_explicit_keyword_only_api_has_no_defaults(self):
        parameters = inspect.signature(self._api()).parameters
        self.assertEqual(set(parameters), {"corpus", "chain_registry", "chain_names"})
        for parameter in parameters.values():
            self.assertEqual(parameter.kind, inspect.Parameter.KEYWORD_ONLY)
            self.assertIs(parameter.default, inspect.Parameter.empty)

    def test_architecture_distinguishes_source_capture_from_qa_and_live_replay(self):
        architecture = (Path(__file__).resolve().parents[1] / "docs/ARCHITECTURE.md").read_text()
        for phrase in ("capture_native_history", "sia-native-source-capture-v1",
                       "inspected-only", "no QA", "idle-gist admission"):
            self.assertIn(phrase, architecture)

    def test_shared_source_authority_nonclaims_have_one_production_definition(self):
        source = ast.parse(inspect.getsource(self.bench))
        literals = [node.value for node in ast.walk(source)
                    if isinstance(node, ast.Constant) and type(node.value) is str]
        for non_claim in SOURCE_AUTHORITY_NON_CLAIMS:
            with self.subTest(non_claim=non_claim):
                self.assertEqual(literals.count(non_claim), 1,
                                 "source and QA manifests must share their authority wording")

    def test_explicit_source_arguments_cannot_select_ambient_defaults_or_another_owner(self):
        function = self._api()
        valid = {"corpus": str(self.corpus), "chain_registry": self.registry,
                 "chain_names": ["aegis"]}
        cases = [
            ("corpus-none", {"corpus": None}),
            ("corpus-empty", {"corpus": ""}),
            ("corpus-relative", {"corpus": "."}),
            ("corpus-lexical-alias", {"corpus": str(self.corpus) + "/."}),
            ("corpus-other-owner", {"corpus": str(self.root / "other-corpus")}),
            ("registry-none", {"chain_registry": None}),
            ("registry-empty", {"chain_registry": {}}),
            ("registry-list", {"chain_registry": list(self.registry.items())}),
            ("names-none", {"chain_names": None}),
            ("names-empty", {"chain_names": []}),
            ("names-string", {"chain_names": "aegis"}),
            ("names-tuple", {"chain_names": ("aegis",)}),
            ("names-duplicate", {"chain_names": ["aegis", "aegis"]}),
            ("names-unknown", {"chain_names": ["aegis", "missing-required-chain"]}),
        ]
        forbidden = mock.Mock(side_effect=AssertionError("implicit source authority reached snapshot"))
        with self._source_only(), \
                mock.patch.object(self.bench, "_snapshot_chains", forbidden), \
                mock.patch.object(self.lib, "_chain_cmds", forbidden):
            for label, changes in cases:
                with self.subTest(argument=label), self.assertRaises(REFUSALS):
                    function(**dict(valid, **changes))
        forbidden.assert_not_called()

    def test_requested_chain_iterator_is_rejected_without_consuming_it(self):
        function = self._api()

        class ForbiddenIterator:
            def __iter__(self):
                raise AssertionError("unadmitted requested-source iterator was consumed")

        forbidden = mock.Mock(side_effect=AssertionError("snapshot before requested-roster admission"))
        with self._source_only(), mock.patch.object(self.bench, "_snapshot_chains", forbidden), \
                self.assertRaises(REFUSALS):
            function(corpus=str(self.corpus), chain_registry=self.registry,
                     chain_names=ForbiddenIterator())
        forbidden.assert_not_called()

    def test_complete_requested_chain_roster_is_bounded_before_snapshot(self):
        function = self._api()
        registry = {"aegis": self.registry["aegis"],
                    "fixture-other-chain": self.registry["aegis"]}
        names = list(registry)
        boundary = len(self.registry)
        self.assertGreater(len(names), boundary)
        forbidden = mock.Mock(side_effect=AssertionError("snapshot before complete requested-roster cap"))
        with self._source_only(), \
                mock.patch.object(self.bench, "MAX_BENCH_ROWS", boundary), \
                mock.patch.object(self.bench, "_snapshot_chains", forbidden), \
                self.assertRaises(REFUSALS):
            function(corpus=str(self.corpus), chain_registry=registry, chain_names=names)
        forbidden.assert_not_called()

    def test_real_source_capture_has_no_qa_engine_or_artifact_path(self):
        self._api()
        # Permit the actual owner infrastructure, then require the entire
        # private fixture roster/bytes to stay fixed across source capture.
        with self.lib.corpus_owner():
            pass
        root_before = _tree_bytes(self.root)
        before = {"corpus": _tree_bytes(self.corpus),
                  "ledger": _tree_bytes(Path(self.fixture.state))}
        capture = self._call()
        self._assert_capture(capture)
        self.assertEqual(_tree_bytes(self.corpus), before["corpus"])
        self.assertEqual(_tree_bytes(Path(self.fixture.state)), before["ledger"])
        self.assertEqual(_tree_bytes(self.root), root_before)
        self.assertTrue(capture["chains"])
        self.assertTrue(capture["events"])
        self.assertTrue(capture["pages"])
        self.assertFalse(any(item["status"] == "refused" for item in capture["diagnostics"]))

    def test_complete_native_rows_and_chain_receipt_are_not_qa_filtered(self):
        rows = self.fixture._signed_rows()
        capture = self._call()
        self.assertEqual([event["row"] for event in capture["events"]], rows)
        chain = next(item for item in capture["chains"] if item["chain"] == "aegis")
        self.assertEqual(chain["row_count"], len(rows))
        self.assertEqual(chain["ledger_sha256"], sha(Path(self.registry["aegis"][0]).read_bytes()))
        self.assertEqual(chain["verifier_sha256"], sha(Path(self.registry["aegis"][1]).read_bytes()))
        self.assertTrue(chain["launch_contract_sha256"])
        self.assertIs(chain["ledger_final_lf"], True)
        for event, row in zip(capture["events"], rows):
            self.assertEqual(event["chain"], "aegis")
            self.assertEqual(event["seq"], row[0])
            self.assertEqual(event["entry_hash"], self.bench._entry_hash(row))
            if row[2].startswith("GENESIS:"):
                self.assertIsNone(event["projection"])
                self.assertEqual(event["retention"]["status"], "not-projected")
            else:
                projected = self.lib.signed_ledger_event_projection("aegis", row)
                self.assertEqual(event["projection"]["event_id"], self.lib.event_memory_identity(projected))
                self.assertEqual(event["projection"]["summary"], projected.summary)

    def test_retained_missing_and_lineage_only_states_remain_distinct(self):
        self.fixture._replace_marker_with_split_decoys("1")
        consolidated = self.fixture._consolidate_sequence_fixture("3", retain_exemplar=False)
        capture = self._call()
        events = {event["seq"]: event for event in capture["events"]}
        self.assertEqual(events["0"]["retention"]["status"], "not-projected")
        self.assertEqual(events["1"]["retention"]["status"], "no-admitted-witness")
        self.assertEqual(events["2"]["retention"]["status"], "retained")
        self.assertEqual(events["3"]["retention"]["status"], "lineage-only")
        self.assertIsNone(events["1"]["retention"]["retrieval_excerpt"])
        self.assertIsNone(events["3"]["retention"]["retrieval_excerpt"])
        witness = next(item for item in capture["witness_files"]
                       if item["path"] == consolidated["index_rel"])
        self.assertEqual(base64.b64decode(witness["content_base64"], validate=True),
                         consolidated["index_raw"])
        self.assertEqual([event["row"] for event in capture["events"]], self.fixture._signed_rows())
        self.assertTrue(capture["witness_coverage"])
        self.assertTrue(capture["question_coverage"])

    def test_full_raw_unicode_origin_and_inspected_page_are_retained(self):
        source = self.fixture._source()
        raw = source.read_bytes().replace(b"---\n", b"---\norigin: model\n", 1)
        raw += "\r\nFULL CAPTURE TAIL Ω\u0085and\u2028unchanged\r\n".encode("utf-8")
        source.write_bytes(raw)
        sibling = self.fixture._source("2026-01-01-part-2")
        sibling_raw = ("---\ntype: event-day\norigin: model\ndate: 2026-01-01\n"
                       "sia_shard: 2\n---\n## Log\n- unrelated inspected note\n").encode("utf-8")
        sibling.write_bytes(sibling_raw)
        capture = self._call()
        pages = {page["slug"]: page for page in capture["pages"]}
        page = pages["events/aegis/2026-01-01"]
        self.assertEqual(page["text"].encode("utf-8"), raw)
        self.assertEqual(page["sha256"], sha(raw))
        self.assertEqual(page["size"], len(raw))
        self.assertEqual(page["origin"], "model")
        self.assertEqual(page["role"], "answer-witness")
        inspected = pages["events/aegis/2026-01-01-part-2"]
        self.assertEqual(inspected["text"].encode("utf-8"), sibling_raw)
        self.assertEqual(inspected["role"], "inspected-only")
        self.assertEqual(inspected["origin"], "model")
        first_identity = capture["dataset_id"]
        sibling.write_bytes(sibling_raw + b"\nchanged inspected-only tail\n")
        changed = self._call()
        self.assertNotEqual(changed["dataset_id"], first_identity,
                            "source identity must bind inspected-only pages too")

    def test_no_answer_witness_is_valid_source_capture_not_a_qa_gate(self):
        rows = self.fixture._signed_rows()
        for row in rows:
            if not row[2].startswith("GENESIS:"):
                self.fixture._replace_marker_with_split_decoys(row[0])
        capture = self._call()
        self._assert_capture(capture)
        self.assertEqual([event["row"] for event in capture["events"]], rows)
        self.assertTrue(capture["pages"])
        self.assertTrue(all(page["role"] == "inspected-only" for page in capture["pages"]))
        self.assertFalse(any(event["retention"]["projected_event_retained"]
                             for event in capture["events"]))

    def test_unknown_required_chain_refuses_instead_of_partial_success(self):
        self._api()
        with self.assertRaises(REFUSALS):
            self._call(names=["aegis", "missing-required-chain"])

    def test_missing_ledger_and_missing_required_page_provenance_refuse(self):
        self._api()
        source = Path(self.registry["aegis"][0])
        source.rename(self.root / "retained-ledger.tsv")
        with self.assertRaises(REFUSALS):
            self._call()
        (self.root / "retained-ledger.tsv").rename(source)
        for page in self.corpus.glob("events/aegis/*.md"):
            page.rename(self.root / ("retained-" + page.name))
        with self.assertRaises(REFUSALS):
            self._call()

    def test_malformed_source_bytes_and_missing_receipt_fields_refuse(self):
        self._api()
        source = self.fixture._source()
        original = source.read_bytes()
        source.write_bytes(original + b"\xff")
        with self.assertRaises(REFUSALS):
            self._call()
        source.write_bytes(original)
        real_snapshot = self.bench._snapshot_chains

        def omit_receipt(**kwargs):
            snapshots, diagnostics = real_snapshot(**kwargs)
            snapshots[0].pop("verifier_sha256")
            return snapshots, diagnostics

        with mock.patch.object(self.bench, "_snapshot_chains", side_effect=omit_receipt), \
                self.assertRaises(REFUSALS):
            self._call()

    def test_source_symlink_is_not_followed(self):
        self._api()
        source = self.fixture._source()
        retained = self.root / "retained-source.md"
        source.rename(retained)
        source.symlink_to(retained)
        with self.assertRaises(REFUSALS):
            self._call()

    def test_real_owner_covers_snapshot_cache_and_capture_admission(self):
        self._api()
        real_snapshot = self.bench._snapshot_chains
        real_resolve = self.bench._CorpusWitnessResolver.resolve
        real_build = self.history.build_capture
        real_admit = self.history.admit_capture
        observed = []

        def snapshot(**kwargs):
            self._assert_owned()
            observed.append("snapshot")
            return real_snapshot(**kwargs)

        def resolve(resolver, event):
            self._assert_owned()
            observed.append("witness")
            return real_resolve(resolver, event)

        def build(**kwargs):
            self._assert_owned()
            observed.append("build")
            result = real_build(**kwargs)
            self._assert_owned()
            return result

        def admit(value):
            self._assert_owned()
            observed.append("admit")
            return real_admit(value)

        with mock.patch.object(self.bench, "_snapshot_chains", side_effect=snapshot), \
                mock.patch.object(self.bench._CorpusWitnessResolver, "resolve", resolve), \
                mock.patch.object(self.history, "build_capture", side_effect=build), \
                mock.patch.object(self.history, "admit_capture", side_effect=admit):
            capture = self._call()
        self.assertEqual(observed[0], "snapshot")
        self.assertLess(observed.index("witness"), observed.index("build"))
        self.assertLess(observed.index("build"), observed.index("admit"))
        self._assert_released()
        self._assert_capture(capture)

    def test_source_capture_reuses_existing_owner_and_releases_on_refusal(self):
        self._api()
        with self.lib.corpus_owner() as owner:
            before_depth = self.lib._CORPUS_OWNER_DEPTH.get()
            capture = self._call()
            self.assertEqual(self.lib._CORPUS_OWNER_FD.get(), owner)
            self.assertEqual(self.lib._CORPUS_OWNER_DEPTH.get(), before_depth)
            self._assert_owned()
            self._assert_capture(capture)
        self._assert_released()
        with mock.patch.object(self.bench, "_snapshot_chains",
                               side_effect=ValueError("fixture source refusal")), \
                self.assertRaises(REFUSALS):
            self._call()
        self._assert_released()

    def test_complete_cache_is_handed_to_real_capture_without_new_file_reads(self):
        self._api()
        real_build = self.history.build_capture
        captured_inputs = []

        def build(**kwargs):
            self._assert_owned()
            resolver = kwargs["resolver"]
            self.assertTrue(resolver.page_cache)
            expected_pages = {page["slug"]: page["text"].encode("utf-8")
                              for page in resolver.page_cache.values()}
            expected_witnesses = {path: item["raw"]
                                  for path, item in resolver.witness_files.items()}
            captured_inputs.append((kwargs, expected_pages, expected_witnesses))
            with mock.patch.object(self.bench, "_read_nofollow_regular",
                                   side_effect=AssertionError("source reread after cache handoff")), \
                    mock.patch.object(self.bench._CorpusWitnessResolver, "_read_page",
                                      side_effect=AssertionError("page cache was not consumed directly")), \
                    mock.patch.object(self.bench._CorpusWitnessResolver, "_read_index",
                                      side_effect=AssertionError("index cache was not consumed directly")):
                return real_build(**kwargs)

        self.fixture._consolidate_sequence_fixture("3", retain_exemplar=False)
        with mock.patch.object(self.history, "build_capture", side_effect=build):
            capture = self._call()
        self.assertEqual(len(captured_inputs), 1)
        inputs, pages, witnesses = captured_inputs[0]
        self.assertEqual({page["slug"]: page["text"].encode("utf-8")
                          for page in capture["pages"]}, pages)
        self.assertEqual({item["path"]: base64.b64decode(item["content_base64"], validate=True)
                          for item in capture["witness_files"]}, witnesses)
        original = canonical(capture)
        # Post-return cache mutation cannot rewrite a detached capture.
        inputs["resolver"].page_cache.clear()
        inputs["snapshots"][0]["rows"][0][3] = "changed supplied fixture cache"
        self.assertEqual(canonical(capture), original)

    def test_real_keeper_still_uses_bound_descriptors_and_discards_output(self):
        self._api()
        real_run = self.lib._run_bounded_text_process
        observed = []

        def execute(command, **kwargs):
            self._assert_owned()
            observed.append(list(command))
            self.assertTrue(all(command[index].startswith("/proc/self/fd/")
                                for index in (0, 1)))
            self.assertNotIn(self.registry["aegis"][0], command)
            self.assertNotIn(self.registry["aegis"][1], command)
            self.assertTrue(kwargs["pass_fds"])
            self.assertIs(kwargs["retain_output"], False)
            self.assertIs(kwargs["isolate_process_tree"], True)
            self.assertEqual(kwargs["output_limit"], self.lib.MAX_CONFIG_BYTES)
            self.assertEqual(set(kwargs["env"]), {"HOME", "TMPDIR", "PATH", "LANG", "LC_ALL"})
            self.assertEqual(os.listdir(kwargs["cwd"]), [])
            return real_run(command, **kwargs)

        with mock.patch.object(self.lib, "_run_bounded_text_process", side_effect=execute):
            capture = self._call()
        self.assertTrue(observed)
        self._assert_capture(capture)

    def test_generation_change_after_real_keeper_refuses_complete_capture(self):
        self._api()
        real_run = self.lib._run_bounded_text_process
        ledger = Path(self.registry["aegis"][0])

        def execute(command, **kwargs):
            result = real_run(command, **kwargs)
            raw = ledger.read_bytes()
            ledger.rename(self.root / "retained-verified-ledger.tsv")
            ledger.write_bytes(raw)
            return result

        with mock.patch.object(self.lib, "_run_bounded_text_process", side_effect=execute), \
                self.assertRaises(REFUSALS):
            self._call()

    def test_existing_source_and_capture_caps_refuse_without_qa_or_fallback(self):
        self._api()
        for owner, name in (
                (self.bench, "MAX_BENCH_LEDGER_BYTES"),
                (self.bench, "MAX_BENCH_VERIFIER_BYTES"),
                (self.bench, "MAX_BENCH_AGGREGATE_BYTES"),
                (self.bench, "MAX_BENCH_ROWS"),
                (self.bench, "MAX_BENCH_SOURCE_PAGE_BYTES"),
                (self.bench, "MAX_BENCH_SOURCE_PAGES"),
                (self.bench, "MAX_BENCH_SOURCE_BYTES"),
                (self.history, "MAX_CAPTURE_BYTES")):
            with self.subTest(cap=name), mock.patch.object(owner, name, 1), \
                    self.assertRaises(REFUSALS):
                self._call()

    def test_capacity_manifest_retains_the_original_complete_policy(self):
        capture = self._call()
        self.assertEqual(capture["capacity_policy"], {
            "kind": "complete-snapshot-refusal-v1",
            "ledger_bytes_per_chain": self.bench.MAX_BENCH_LEDGER_BYTES,
            "verifier_bytes_per_chain": self.bench.MAX_BENCH_VERIFIER_BYTES,
            "declared_input_bytes_each": self.bench.MAX_BENCH_CHAIN_INPUT_BYTES,
            "snapshot_aggregate_bytes": self.bench.MAX_BENCH_AGGREGATE_BYTES,
            "ledger_rows_aggregate": self.bench.MAX_BENCH_ROWS,
            "source_page_bytes": self.bench.MAX_BENCH_SOURCE_PAGE_BYTES,
            "source_pages": self.bench.MAX_BENCH_SOURCE_PAGES,
            "witness_files": self.bench.MAX_BENCH_ROWS,
            "source_page_aggregate_bytes": self.bench.MAX_BENCH_SOURCE_BYTES,
            "candidate_questions": self.bench.MAX_BENCH_CANDIDATE_QUESTIONS,
            "negative_pair_cross_product": self.bench.MAX_BENCH_NEGATIVE_PAIRS,
            "artifact_bytes_each": self.bench.MAX_BENCH_FILE_BYTES,
            "artifact_aggregate_bytes": self.bench.MAX_BENCH_AGGREGATE_BYTES,
        })


def root_characterize_legacy_bytes():
    """Root-run only: produce an unfiltered pre-extraction byte oracle.

    Returns bytes, does not choose a persistent output path or update a golden.
    Root must retain and independently wire-pin this result before extraction.
    This invokes ONLY the existing APIs, so it can run before the new API exists.
    The temporary dataset outputs are required observations of legacy export
    behavior, not allowed side effects of the proposed capture-only API.
    """
    case = NativeHistoryCapture(methodName="runTest")
    try:
        # setUp does not require the missing API. It gives the same signed
        # fixture an actual private owner/lifecycle root for this old API run.
        case.setUp()
        fixture = case.fixture
        with case.lib.corpus_owner():
            products = {}
            for name, captured in (("default", False), ("opt-in", True)):
                bundle = (fixture._enabled_bundle() if captured else fixture._legacy_bundle())
                output = fixture.root / ("legacy-characterization-" + name)
                fixture.bench.write_dataset(bundle, str(output), corpus=fixture.corpus)
                artifacts = fixture._published_artifacts(output, captured=captured)
                products[name] = {
                    "bundle_canonical_base64": base64.b64encode(canonical(bundle)).decode("ascii"),
                    "files": {leaf: {
                        "mode": stat.S_IMODE(path.lstat().st_mode),
                        "raw_base64": base64.b64encode(path.read_bytes()).decode("ascii"),
                    } for leaf, path in sorted(artifacts.items())},
                }
            return canonical({
                "schema": "sia-native-capture-legacy-characterization-v1",
                "fixture_sources": {
                    "ledger": _tree_bytes(Path(fixture.state)),
                    "corpus": _tree_bytes(Path(fixture.corpus)),
                    "registered_verifier_base64": base64.b64encode(
                        Path(fixture.registry["aegis"][1]).read_bytes()).decode("ascii"),
                },
                "products": products,
            })
    finally:
        case.doCleanups()


def root_compare_legacy_bytes(*, expected, expected_sha256):
    """Root supplies original whole bytes and independently retained wire pin."""
    if type(expected) is not bytes or type(expected_sha256) is not str \
            or sha(expected) != expected_sha256:
        raise AssertionError("legacy characterization authority differs")
    observed = root_characterize_legacy_bytes()
    if observed != expected:
        raise AssertionError(
            "legacy bytes changed: inspect the complete original and new packets; "
            "do not regenerate the golden or filter mismatching fields")


if __name__ == "__main__":
    unittest.main()
